export const data = [
  {
    brand: 'ASUS',
    model: 'Zenbook Pro 15 UX550GD-BO009R',
    processor: 'Intel Core i7',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '12 ГБ',
    mediaType: 'SSD',
    hddCapacity: '450 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'Zenbook Pro 15 UX550GD-BO009R',
    processor: 'Intel Core i5 ',
    cores: 'Двухъядерный',
    size: '14',
    screen: 'WXGA (1366x768)',
    memory: '4 ГБ ',
    mediaType: 'HDD ',
    hddCapacity: '500 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'ROG GL503VM',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '6 ГБ',
    mediaType: 'SSD',
    hddCapacity: '250 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'ROG GL503VM',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '14',
    screen: 'WXGA (1366x768)',
    memory: '4 ГБ ',
    mediaType: 'HDD ',
    hddCapacity: '1000 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'ZenBook Flip UX561UN-BO006T',
    processor: 'Intel Core i7',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '8 ГБ',
    mediaType: 'SSD',
    hddCapacity: '250 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'ZenBook Flip UX561UN-BO006T',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WXGA (1366x768)',
    memory: '6 ГБ',
    mediaType: 'HDD ',
    hddCapacity: '750 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'TUF Gaming FX504GD',
    processor: 'Intel Core i7',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '12 ГБ',
    mediaType: 'SSD',
    hddCapacity: '500 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'TUF Gaming FX504GD',
    processor: 'Intel Core i3',
    cores: 'Двухъядерный',
    size: '14',
    screen: 'WXGA (1366x768)',
    memory: '4 ГБ ',
    mediaType: 'HDD ',
    hddCapacity: '750 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'VivoBook 14 X411UF',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '6 ГБ',
    mediaType: 'HDD ',
    hddCapacity: '500 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'X302UV',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '6 ГБ',
    mediaType: 'HDD ',
    hddCapacity: '500 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'X302UV',
    processor: 'Intel Core i3',
    cores: 'Двухъядерный',
    size: '12.5',
    screen: 'WXGA (1366x768)',
    memory: '4 ГБ ',
    mediaType: 'HDD ',
    hddCapacity: '250 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'VivoBook X542UF',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '14',
    screen: 'WUXGA (1920x1080)',
    memory: '6 ГБ',
    mediaType: 'SSD',
    hddCapacity: '250 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'ASUS',
    model: 'VivoBook X542UF',
    processor: 'Intel Core i3',
    cores: 'Двухъядерный',
    size: '12.5',
    screen: 'WXGA (1366x768)',
    memory: '4 ГБ ',
    mediaType: 'HDD ',
    hddCapacity: '250 ГБ',
    img: 'asus.jpg'
  },
  {
    brand: 'Apple',
    model: 'MacBook Pro Touch Bar Retina A1706',
    processor: 'Intel Core i7',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'Retina (2560x1600) ',
    memory: '12 ГБ',
    mediaType: 'SSD',
    hddCapacity: '500 ГБ',
    img: 'apple.jpg'
  },
  {
    brand: 'Apple',
    model: 'MacBook Pro Touch Bar Retina A1706',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'Retina (2560x1600) ',
    memory: '6 ГБ',
    mediaType: 'SSD',
    hddCapacity: '250 ГБ',
    img: 'apple.jpg'
  },
  {
    brand: 'Apple',
    model: 'MacBook Pro Retina A1708',
    processor: 'Intel Core i7',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'Retina (2560x1600) ',
    memory: '8 ГБ',
    mediaType: 'SSD',
    hddCapacity: '250 ГБ',
    img: 'apple.jpg'
  },
  {
    brand: 'Apple',
    model: 'MacBook Pro Retina A1708',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '14',
    screen: 'Retina (2560x1600) ',
    memory: '6 ГБ',
    mediaType: 'SSD',
    hddCapacity: '250 ГБ',
    img: 'apple.jpg'
  },
  {
    brand: 'HP',
    model: 'EliteBook 1040 G4',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '6 ГБ',
    mediaType: 'HDD ',
    hddCapacity: '1000 ГБ',
    img: 'hp.jpg'
  },
  {
    brand: 'HP',
    model: 'EliteBook x360 1030 G2',
    processor: 'Intel Core i7',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '12 ГБ',
    mediaType: 'HDD ',
    hddCapacity: '1000 ГБ',
    img: 'hp.jpg'
  },
  {
    brand: 'HP',
    model: 'EliteBook 850 G5',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '6 ГБ',
    mediaType: 'HDD ',
    hddCapacity: '500 ГБ',
    img: 'hp.jpg'
  },
  {
    brand: 'HP',
    model: 'EliteBook 840 G4',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '6 ГБ',
    mediaType: 'HDD ',
    hddCapacity: '500 ГБ',
    img: 'hp.jpg'
  },
  {
    brand: 'HP',
    model: 'EliteBook 1040 G3',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '4 ГБ ',
    mediaType: 'HDD ',
    hddCapacity: '500 ГБ',
    img: 'hp.jpg'
  },
  {
    brand: 'HP',
    model: 'Spectre 13-af011ur',
    processor: 'Intel Core i3',
    cores: 'Двухъядерный',
    size: '12.5',
    screen: 'WXGA (1366x768)',
    memory: '4 ГБ ',
    mediaType: 'HDD ',
    hddCapacity: '250 ГБ',
    img: 'hp.jpg'
  },
  {
    brand: 'HP',
    model: 'Envy 13-ad028ur',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '4 ГБ ',
    mediaType: 'SSD',
    hddCapacity: '500 ГБ',
    img: 'hp.jpg'
  },
  {
    brand: 'HP',
    model: 'Probook 440 G5',
    processor: 'Intel Core i5 ',
    cores: 'Четырехъядерный',
    size: '15.6',
    screen: 'WUXGA (1920x1080)',
    memory: '4 ГБ ',
    mediaType: 'SSD',
    hddCapacity: '500 ГБ',
    img: 'hp.jpg'
  }
];
